version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: "UserSignUp/Dockerfile"
    image: emilwitt/r_a_d-apihub:${DEPLOY_NUMBER}
      ports:
      - 8050:80 
    depends_on:
      - seq
      - zipkin
      - rmq
  web:
    build:
      context: .
      dockerfile: "Frontend/Dockerfile"    
    image: emilwitt/r_a_d-webhub:${DEPLOY_NUMBER}
    ports:
      - 8040:80 
    depends_on:
      - seq
      - zipkin
      - rmq

