version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: "UserSignUp/Dockerfile"
    ports:
      - 9000:80

  web:
    build:
      context: .
      dockerfile: "Frontend/Dockerfile"
    ports:
      - 9001:80

